export const styles = {
    navbar: (visible: boolean) => `position-fixed top-0 start-0 w-100 glass-navbar${visible ? '' : ' navbar-hidden'}`,
    inner: 'container py-2 d-flex justify-content-between align-items-center container-main',
    brand: 'd-flex align-items-center gap-2 brand-link',
    brandLogo: 'brand-logo',
    brandDesktop: 'fw-bolder navbar-brand-text d-none d-md-block brand-text-desktop',
    brandMobile: 'fw-bolder navbar-brand-text d-block d-md-none brand-text-mobile',
    menuWrap: 'position-relative',
    menuTrigger: 'btn menu-trigger d-flex align-items-center justify-content-center pressable-btn',
    menuIcon: (open: boolean) => `menu-icon${open ? ' open' : ''}`,
    dropdown: 'position-absolute end-0 mt-2 rounded-4 overflow-hidden glass-dropdown animate-slide-fade menu-dropdown',
    dropdownInner: 'menu-dropdown-inner',
    darkToggleBtn: 'btn w-100 text-start px-3 py-2 menu-action fw-semibold d-flex align-items-center justify-content-between dark-toggle-btn menu-item-btn',
    darkToggleLabel: 'd-flex align-items-center gap-2',
    darkTogglePill: (active: boolean) => `dark-toggle-pill${active ? ' active' : ''}`,
    darkToggleThumb: 'dark-toggle-thumb',
    divider: 'menu-divider',
    switchBtn: 'btn text-decoration-none w-100 text-start px-3 py-2 pressable-btn menu-action fw-semibold menu-text menu-item-btn',
    switchIcon: 'me-2',
    logoutBtn: 'btn text-decoration-none text-danger w-100 text-start px-3 py-2 pressable-btn menu-action fw-semibold menu-item-btn',
    logoutIcon: 'me-2',
};
