export const styles = {
    wrapper: 'mb-5',
    header: 'd-flex flex-column flex-md-row justify-content-between align-items-md-center mb-4 gap-3',
    headerLeft: '',
    titleRow: 'd-flex align-items-center gap-2',
    icon: 'icon-box-md',
    title: 'fw-bolder mb-0 page-title',
    subtitle: 'text-muted small fw-semibold',
    createBtn: 'btn btn-primary fw-bold shadow-sm rounded-3 px-4 py-2 pressable-btn',
    emptyAlert: 'alert bg-white border-0 shadow-sm rounded-4 p-5 text-center',
    emptyText: 'text-muted fw-bold',
    grid: 'row row-cols-1 row-cols-md-2 row-cols-xl-3 g-4',
    col: 'col section-enter',
    card: 'card h-100 border-0 interactive-card team-card glass-card-sm',
    cardBody: 'card-body p-4 d-flex flex-column',
    cardTop: 'd-flex justify-content-between align-items-start mb-3',
    statusBadge: 'badge bg-primary bg-opacity-10 text-primary rounded-pill px-3 py-2 fw-bold',
    cardTitle: 'card-title fw-bolder text-dark mb-4',
    cardBottom: 'mt-auto',
    capacityRow: 'd-flex justify-content-between text-muted small fw-bold mb-2',
    progress: 'progress progress-slim mb-4',
    progressBar: 'progress-bar bg-primary',
    actionBtn: (acted: boolean) =>
        `btn w-100 fw-bold rounded-3 py-2 pressable-btn d-flex align-items-center justify-content-center gap-2 join-action-btn${acted ? ' btn-secondary' : ' btn-light text-primary'}`,
};
