export const styles = {
    wrapper: 'mb-4',
    header: 'd-flex align-items-center gap-2 mb-3',
    icon: 'icon-box-sm',
    title: 'fw-bold mb-0 menu-text section-label',
    badge: (pulse: boolean) => `fw-bolder rounded-pill d-flex align-items-center gap-1 badge-pending${pulse ? ' pulse' : ''}`,
    emptyCard: 'card border-0 bg-white rounded-4 shadow-sm p-3 d-flex flex-column flex-md-row align-items-md-center justify-content-between interactive-card',
    emptyIconWrap: 'd-flex align-items-center mb-3 mb-md-0',
    emptyIcon: 'icon-circle bg-light me-3',
    emptyTitle: 'fw-bolder text-dark mb-0',
    emptySubtitle: 'text-muted small mt-1',
    emptyArrow: 'btn btn-light rounded-3 fw-bold px-3 py-2 pressable-btn',
    activeCard: 'card border-0 bg-white rounded-4 shadow-sm p-3 d-flex flex-column flex-md-row align-items-md-center justify-content-between interactive-card fade-up card-border-brand',
    activeLeft: 'd-flex align-items-center mb-3 mb-md-0',
    activeIcon: 'icon-circle bg-primary bg-opacity-10 text-primary me-3',
    activeName: 'fw-bolder text-dark mb-0',
    activeMeta: 'd-flex align-items-center gap-2 mt-1 flex-wrap',
    metaText: 'text-muted small',
    positionBadge: 'fw-bold badge-position rounded-pill d-inline-flex align-items-center',
    actions: 'd-flex flex-wrap gap-2 justify-content-md-end',
    nextBtn: (pulse: boolean) => `btn btn-light rounded-3 fw-bold px-3 py-2 pressable-btn${pulse ? ' soft-pulse' : ''}`,
    declineBtn: 'btn btn-light text-danger fw-bold rounded-3 px-4 py-2 pressable-btn',
    acceptBtn: 'btn btn-primary fw-bold rounded-3 px-4 py-2 pressable-btn d-flex align-items-center gap-2',
};
