export const styles = {
    card: 'card border-0 mb-5 fade-up glass-card',
    header: 'card-header bg-transparent border-0 pt-4 pb-0 px-4 px-md-5 d-flex flex-column flex-md-row justify-content-between align-items-md-center',
    headerLeft: 'mb-3 mb-md-0 d-flex align-items-center gap-3',
    icon: 'icon-box-lg',
    badge: 'badge bg-success bg-opacity-10 text-success rounded-pill px-3 py-1 fw-bold mb-1 text-xs',
    title: 'fw-bolder mb-0 page-title',
    headerActions: 'd-flex flex-wrap gap-2',
    leaveBtn: 'btn btn-outline-danger fw-bold rounded-3 px-4 py-2 pressable-btn',
    body: 'card-body p-4 p-md-5',
    supervisorBox: 'mb-5 p-4 bg-light rounded-4 d-flex flex-column flex-md-row justify-content-between align-items-md-center border border-primary border-opacity-25 gap-3',
    supervisorLabel: 'fw-bold text-dark mb-1',
    supervisorValue: 'text-secondary small',
    inviteWrap: 'd-flex align-items-center gap-2 w-100 animate-slide-fade invite-sup-wrap',
    supervisorSelect: 'form-select form-select-sm border-primary border-opacity-25 text-secondary fw-semibold flex-grow-1 supervisor-select',
    cancelBtn: 'btn btn-light btn-sm fw-bold px-3 rounded-3 flex-shrink-0 pressable-btn',
    sendBtn: (state: string) =>
        `btn btn-sm fw-bold rounded-3 shadow-sm d-flex align-items-center justify-content-center gap-2 flex-shrink-0 pressable-btn send-invite-btn${state === 'success' ? ' btn-success text-white' : ' btn-primary'}`,
    inviteSupervisorBtn: 'btn btn-primary btn-sm fw-bold rounded-3 px-4 py-2 pressable-btn',
    membersLabel: 'fw-bold text-muted mb-4 section-label',
    memberList: 'list-group list-group-flush gap-3 mb-3',
    memberRow: 'list-group-item border-0 p-3 bg-light rounded-4 d-flex align-items-center interactive-card',
    memberInfo: 'ms-3 flex-grow-1',
    memberName: 'fw-bold text-dark mb-0 d-flex align-items-center gap-2',
    youBadge: 'badge bg-secondary opacity-50 fw-normal',
    memberId: 'text-muted small',
    memberRight: 'd-flex align-items-center gap-3',
    roleBadge: (isLeader: boolean) =>
        `badge shadow-sm rounded-pill px-3 py-2${isLeader ? ' bg-primary' : ' bg-white text-dark border'}`,
    manageBtn: 'btn btn-sm btn-light text-primary fw-bold px-3 rounded-3 pressable-btn',
    inviteMemberBtn: 'btn btn-light text-primary fw-bold w-100 rounded-4 py-3 mb-5 pressable-btn invite-member-btn',
    docBox: 'p-4 bg-primary bg-opacity-10 rounded-4 d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-3',
    docLabel: 'fw-bold text-primary mb-1',
    docValue: 'text-secondary small',
    docActions: 'd-flex flex-wrap gap-2',
    openLinkBtn: 'btn btn-white text-primary border-0 fw-bold shadow-sm rounded-3 px-4 py-2 bg-white pressable-btn',
    editLinkBtn: 'btn btn-primary fw-bold shadow-sm rounded-3 px-4 py-2 pressable-btn',
};
