export const styles = {
    wrapper: 'mb-4',
    header: 'd-flex align-items-center gap-2 mb-3',
    icon: 'icon-box-sm',
    title: 'fw-bold mb-0 menu-text section-label',
    countBadge: 'fw-bolder rounded-pill d-flex align-items-center gap-1 badge-pending',
    bookBtn: 'btn btn-primary btn-sm fw-bold rounded-3 px-3 ms-auto pressable-btn',
    emptyCard: 'card border-0 bg-white rounded-4 shadow-sm p-3 d-flex flex-column flex-md-row align-items-md-center justify-content-between interactive-card',
    emptyLeft: 'd-flex align-items-center',
    emptyIcon: 'icon-circle bg-light me-3',
    emptyTitle: 'fw-bolder text-dark mb-0',
    emptySubtitle: 'text-muted small mt-1',
    activeCard: 'card border-0 bg-white rounded-4 shadow-sm p-3 d-flex flex-column flex-md-row align-items-md-center justify-content-between interactive-card fade-up card-border-success',
    activeLeft: 'd-flex align-items-center mb-3 mb-md-0',
    activeIcon: 'icon-circle bg-success bg-opacity-10 text-success me-3',
    activeInfo: '',
    activeTitleRow: 'd-flex align-items-center gap-2 mb-1 flex-wrap',
    activeTitle: 'fw-bolder text-dark mb-0',
    upcomingBadge: 'fw-bolder badge-upcoming rounded-pill',
    activeMeta: 'd-flex align-items-center gap-2 flex-wrap',
    metaText: 'text-muted small',
    actions: 'd-flex flex-wrap gap-2 justify-content-md-end',
    editBtn: 'btn btn-light fw-bold rounded-3 px-4 py-2 pressable-btn',
    deleteBtn: 'btn btn-light text-danger fw-bold rounded-3 px-4 py-2 pressable-btn',
};
